### ISSUE TITLE
buildroot-external: no such directory

### ISSUE THREAD

**Issue by axelsimon** [nickaknudson/snapcast-pi#2]
Hi,
I thought I'd give your buildroot snapcast image a go, but I've hit a snag when running the `make` commands:

`make: Entering directory '/home/buildroot/buildroot'
Makefile:200: *** '/home/buildroot/snapcast-pi/buildroot-external': no such file or directory.  Stop.
`
And indeed, from what I can see, /home/buildroot/snapcast-pi doesn't contain a directory called builroot-external. Any ideas?

Thanks!

**Comment by gartensofa** [comment]
Hey there.
Maybe try doing this first and then make again:
`git clone https://github.com/nickaknudson/snapcast-pi.git /home/buildroot/snapcast-pi`

**Comment by nickaknudson** [comment]
@gartensofa is correct - @axelsimon first clone this repository

    git clone https://github.com/nickaknudson/snapcast-pi.git && cd snapcast-pi

**Comment by axelsimon** [comment]
Hi,
I cleared all my docker containers and then followed the instructions in the README (copy pasted every line) and got the same error:
```
make: Entering directory '/home/buildroot/buildroot'
Makefile:190: *** '/home/buildroot/snapcast-pi/buildroot-external': permission denied.  Stop.
```
But even a simple `ls /home/buildroot/snapcast-pi` (even as root) returns an error:
```
buildroot@e2cf0e71f001:~/snapcast-pi$ ls /home/buildroot/snapcast-pi/
ls: cannot open directory '/home/buildroot/snapcast-pi/': Permission denied
```
This made me realise what's causing this situation: docker isn't aware of the SElinux context. You need to  use the [:Z option on mounts](https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/).

So the proper command, to enter the docker container on any system using SElinux (Fedora, RHEL, etc.) is:
 `docker run -it -v $(pwd):/home/buildroot/snapcast-pi:Z -w /home/buildroot/snapcast-pi nickaknudson/buildroot /bin/bash`
