### ISSUE TITLE
How can I cross compile snapcast for already working rpi w/o flashing?

### ISSUE THREAD

**Issue by a-x-** [nickaknudson/snapcast-pi#5]
Can I build just snapcast binary file?

**Comment by nickaknudson** [comment]
Follow the instructions up to the "Build" step and then run:

    make O=~/buildroot-output BR2_DL_DIR=~/buildroot-dl BR2_EXTERNAL=~/snapcast/buildroot:~/snapcast-pi/buildroot-external -C ~/buildroot package/snapcast

**Comment by a-x-** [comment]
Thank you

**Comment by BaReinhard** [comment]
Forgive my ignorance here, but how would I install this on a running version of raspbian Jessie (if that’s even possible)? I tried what was suggested here but I get an exec user error.
